import asyncio
import os
import uuid
from datetime import datetime, timezone
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv

load_dotenv()

# MongoDB connection
mongo_url = os.environ.get("MONGO_URI")
db_name = os.environ.get("DB_NAME", "finez_db")

client = AsyncIOMotorClient(mongo_url)
db = client[db_name]

PLATFORM_PRODUCTS = [
    # --- Side Hustles ---
    {
        "title": "Shopify",
        "description": "Start your own ecommerce business with the world's most popular platform.",
        "why_this_product": "⚡ Start selling for $1/month for the first 3 months",
        "price": 1.0,
        "category": "Side Hustles",
        "type": "affiliate",
        "affiliate_link": "https://www.shopify.com/",
        "affiliate_network": "Direct",
        "image_url": "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800",
        "featured": True,
    },
    {
        "title": "Fiverr",
        "description": "Find the perfect freelance services for your business.",
        "why_this_product": "💰 Hire pros for any task starting at $5",
        "price": 5.0,
        "category": "Side Hustles",
        "type": "affiliate",
        "affiliate_link": "https://www.fiverr.com/",
        "affiliate_network": "Fiverr",
        "image_url": "https://images.unsplash.com/photo-1521791136064-7986c2959210?w=800",
        "featured": False,
    },
    {
        "title": "Upwork",
        "description": "The world's work marketplace for top talent and businesses.",
        "why_this_product": "🌍 Work with the top 3% of freelance talent globally",
        "price": 0.0,
        "category": "Side Hustles",
        "type": "affiliate",
        "affiliate_link": "https://www.upwork.com/",
        "affiliate_network": "Upwork",
        "image_url": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800",
        "featured": False,
    },
    {
        "title": "Etsy",
        "description": "Shop for handmade, vintage, custom, and unique gifts.",
        "why_this_product": "🎨 Turn your hobby into a business - list your first item for $0.20",
        "price": 0.2,
        "category": "Side Hustles",
        "type": "affiliate",
        "affiliate_link": "https://www.etsy.com/",
        "affiliate_network": "Awin",
        "image_url": "https://images.unsplash.com/photo-1513519245088-0e12902e35ca?w=800",
        "featured": False,
    },
    {
        "title": "Amazon Associates",
        "description": "Earn commissions by recommending products from Amazon.",
        "why_this_product": "📦 Earn up to 10% commission on millions of products",
        "price": 0.0,
        "category": "Side Hustles",
        "type": "affiliate",
        "affiliate_link": "https://affiliate-program.amazon.com/",
        "affiliate_network": "Amazon",
        "image_url": "https://images.unsplash.com/photo-1523474253046-2cd2c78a9db1?w=800",
        "featured": True,
    },
    {
        "title": "ClickBank",
        "description": "Leading global retailer and affiliate marketplace.",
        "why_this_product": "🚀 High-converting digital products with up to 75% commission",
        "price": 0.0,
        "category": "Side Hustles",
        "type": "affiliate",
        "affiliate_link": "https://www.clickbank.com/",
        "affiliate_network": "ClickBank",
        "image_url": "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800",
        "featured": False,
    },
    {
        "title": "CJ Affiliate",
        "description": "Global affiliate marketing network specializing in pay-for-performance.",
        "why_this_product": "💼 Partner with the world's most recognized brands",
        "price": 0.0,
        "category": "Side Hustles",
        "type": "affiliate",
        "affiliate_link": "https://www.cj.com/",
        "affiliate_network": "CJ",
        "image_url": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800",
        "featured": False,
    },
    {
        "title": "ShareASale",
        "description": "Trusted affiliate network for over 20 years.",
        "why_this_product": "🤝 Over 25,000 merchants across all categories",
        "price": 0.0,
        "category": "Side Hustles",
        "type": "affiliate",
        "affiliate_link": "https://www.shareasale.com/",
        "affiliate_network": "ShareASale",
        "image_url": "https://images.unsplash.com/photo-1454165833767-027ffea9e772?w=800",
        "featured": False,
    },
    {
        "title": "Printify",
        "description": "Print-on-demand network for ecommerce entrepreneurs.",
        "why_this_product": "👕 Start your clothing brand with zero upfront costs",
        "price": 0.0,
        "category": "Side Hustles",
        "type": "affiliate",
        "affiliate_link": "https://printify.com/",
        "affiliate_network": "Printify",
        "image_url": "https://images.unsplash.com/photo-1527383418406-f85a3b146499?w=800",
        "featured": False,
    },
    {
        "title": "Teespring",
        "description": "Create and sell custom products without any risk or cost.",
        "why_this_product": "🎨 Design and sell custom merch to your fans",
        "price": 0.0,
        "category": "Side Hustles",
        "type": "affiliate",
        "affiliate_link": "https://teespring.com/",
        "affiliate_network": "Teespring",
        "image_url": "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800",
        "featured": False,
    },
    {
        "title": "Gumroad",
        "description": "Sell digital products directly to your audience.",
        "why_this_product": "📦 Perfect for creators - keep more of what you earn",
        "price": 0.0,
        "category": "Side Hustles",
        "type": "affiliate",
        "affiliate_link": "https://gumroad.com/",
        "affiliate_network": "Gumroad",
        "image_url": "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=800",
        "featured": False,
    },
    {
        "title": "Notion Templates",
        "description": "The largest marketplace for Notion templates and setups.",
        "why_this_product": "📓 Passive income - sell your Notion workflows",
        "price": 0.0,
        "category": "Side Hustles",
        "type": "affiliate",
        "affiliate_link": "https://www.notion.so/templates",
        "affiliate_network": "Direct",
        "image_url": "https://images.unsplash.com/photo-1517842645767-c639042777db?w=800",
        "featured": False,
    },

    # --- AI Tools ---
    {
        "title": "Canva Pro",
        "description": "Design everything with Canva Pro's advanced AI features.",
        "why_this_product": "🎨 Design like a pro with Magic Studio AI tools",
        "price": 12.99,
        "category": "AI Tools",
        "type": "affiliate",
        "affiliate_link": "https://www.canva.com/pro/",
        "affiliate_network": "Impact",
        "image_url": "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800",
        "featured": True,
    },
    {
        "title": "Jasper",
        "description": "AI copywriter for marketing teams and creators.",
        "why_this_product": "✍️ Create high-quality content 10x faster",
        "price": 39.0,
        "category": "AI Tools",
        "type": "affiliate",
        "affiliate_link": "https://www.jasper.ai/",
        "affiliate_network": "Direct",
        "image_url": "https://images.unsplash.com/photo-1675557009875-436f2976306e?w=800",
        "featured": True,
    },
    {
        "title": "Copy.ai",
        "description": "AI-powered copywriter for all your marketing needs.",
        "why_this_product": "🚀 Generate high-converting marketing copy in seconds",
        "price": 36.0,
        "category": "AI Tools",
        "type": "affiliate",
        "affiliate_link": "https://www.copy.ai/",
        "affiliate_network": "Direct",
        "image_url": "https://images.unsplash.com/photo-1673187115862-d81b2394747c?w=800",
        "featured": False,
    },
    {
        "title": "Notion AI",
        "description": "Write faster, think bigger, and augment your creativity inside Notion.",
        "why_this_product": "🧠 Your personal AI assistant inside your workspace",
        "price": 10.0,
        "category": "AI Tools",
        "type": "affiliate",
        "affiliate_link": "https://www.notion.so/product/ai",
        "affiliate_network": "Direct",
        "image_url": "https://images.unsplash.com/photo-1517842645767-c639042777db?w=800",
        "featured": False,
    },
    {
        "title": "Grammarly",
        "description": "Improve your writing with Grammarly's AI communication assistant.",
        "why_this_product": "✍️ Write with confidence and clarity everywhere",
        "price": 12.0,
        "category": "AI Tools",
        "type": "affiliate",
        "affiliate_link": "https://www.grammarly.com/",
        "affiliate_network": "Direct",
        "image_url": "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800",
        "featured": False,
    },
    {
        "title": "Pictory",
        "description": "AI video creation for content marketers.",
        "why_this_product": "🎬 Turn scripts and blog posts into videos automatically",
        "price": 19.0,
        "category": "AI Tools",
        "type": "affiliate",
        "affiliate_link": "https://pictory.ai/",
        "affiliate_network": "Direct",
        "image_url": "https://images.unsplash.com/photo-1536240478700-b869070f9279?w=800",
        "featured": False,
    },
    {
        "title": "Writesonic",
        "description": "Best AI writer for creating SEO-friendly content.",
        "why_this_product": "📈 Rank higher with AI-optimized articles and blogs",
        "price": 13.0,
        "category": "AI Tools",
        "type": "affiliate",
        "affiliate_link": "https://writesonic.com/",
        "affiliate_network": "Direct",
        "image_url": "https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?w=800",
        "featured": False,
    },
    {
        "title": "Midjourney",
        "description": "State-of-the-art AI image generator for artists and designers.",
        "why_this_product": "🖼️ Create breathtaking art from simple text prompts",
        "price": 10.0,
        "category": "AI Tools",
        "type": "affiliate",
        "affiliate_link": "https://www.midjourney.com/",
        "affiliate_network": "Direct",
        "image_url": "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800",
        "featured": True,
    },
    {
        "title": "ElevenLabs",
        "description": "The most realistic AI voice generator and text-to-speech.",
        "why_this_product": "🎙️ Human-like voices for your videos and podcasts",
        "price": 5.0,
        "category": "AI Tools",
        "type": "affiliate",
        "affiliate_link": "https://elevenlabs.io/",
        "affiliate_network": "Direct",
        "image_url": "https://images.unsplash.com/photo-1589903303941-0677e59db0a8?w=800",
        "featured": False,
    },
    {
        "title": "Runway ML",
        "description": "Next-generation AI tools for video and image generation.",
        "why_this_product": "🎥 The future of video editing is here with Gen-2",
        "price": 12.0,
        "category": "AI Tools",
        "type": "affiliate",
        "affiliate_link": "https://runwayml.com/",
        "affiliate_network": "Direct",
        "image_url": "https://images.unsplash.com/photo-1492724441997-5dc865305da7?w=800",
        "featured": False,
    },

    # --- Learn ---
    {
        "title": "Udemy",
        "description": "The leading global marketplace for learning and instruction.",
        "why_this_product": "🎓 Learn any skill - courses starting at $12.99",
        "price": 12.99,
        "category": "Learn",
        "type": "affiliate",
        "affiliate_link": "https://www.udemy.com/",
        "affiliate_network": "Rakuten",
        "image_url": "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800",
        "featured": True,
    },
    {
        "title": "Coursera",
        "description": "Learn from the world's best universities and companies.",
        "why_this_product": "📜 Get certified by Google, IBM, and top universities",
        "price": 49.0,
        "category": "Learn",
        "type": "affiliate",
        "affiliate_link": "https://www.coursera.org/",
        "affiliate_network": "Impact",
        "image_url": "https://images.unsplash.com/photo-1516321497487-e288fb19713f?w=800",
        "featured": True,
    },
    {
        "title": "Skillshare",
        "description": "Online classes for creative and curious people.",
        "why_this_product": "🎨 Explore thousands of creative classes for free",
        "price": 14.0,
        "category": "Learn",
        "type": "affiliate",
        "affiliate_link": "https://www.skillshare.com/",
        "affiliate_network": "Impact",
        "image_url": "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800",
        "featured": False,
    },
    {
        "title": "MasterClass",
        "description": "Learn from the best in the world.",
        "why_this_product": "⭐ Learn from Gordon Ramsay, Natalie Portman, and more",
        "price": 15.0,
        "category": "Learn",
        "type": "affiliate",
        "affiliate_link": "https://www.masterclass.com/",
        "affiliate_network": "Impact",
        "image_url": "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=800",
        "featured": False,
    },
    {
        "title": "Codecademy",
        "description": "Learn to code interactively, for free.",
        "why_this_product": "💻 Build your career in tech - learn by doing",
        "price": 19.99,
        "category": "Learn",
        "type": "affiliate",
        "affiliate_link": "https://www.codecademy.com/",
        "affiliate_network": "Impact",
        "image_url": "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800",
        "featured": False,
    },
    {
        "title": "LinkedIn Learning",
        "description": "Learn the most in-demand business, tech, and creative skills.",
        "why_this_product": "💼 Advance your career with personalized skill paths",
        "price": 29.99,
        "category": "Learn",
        "type": "affiliate",
        "affiliate_link": "https://www.linkedin.com/learning/",
        "affiliate_network": "LinkedIn",
        "image_url": "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=800",
        "featured": False,
    },
    {
        "title": "Khan Academy",
        "description": "Free online courses, lessons & practice.",
        "why_this_product": "🌍 Free world-class education for anyone, anywhere",
        "price": 0.0,
        "category": "Learn",
        "type": "affiliate",
        "affiliate_link": "https://www.khanacademy.org/",
        "affiliate_network": "None",
        "image_url": "https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?w=800",
        "featured": False,
    },
    {
        "title": "Duolingo",
        "description": "The world's best way to learn a language.",
        "why_this_product": "🦉 Learn a language for free in just 5 minutes a day",
        "price": 0.0,
        "category": "Learn",
        "type": "affiliate",
        "affiliate_link": "https://www.duolingo.com/",
        "affiliate_network": "Direct",
        "image_url": "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800",
        "featured": False,
    },
    {
        "title": "DataCamp",
        "description": "Learn data science and AI online.",
        "why_this_product": "📊 Master data skills at your own pace",
        "price": 25.0,
        "category": "Learn",
        "type": "affiliate",
        "affiliate_link": "https://www.datacamp.com/",
        "affiliate_network": "Impact",
        "image_url": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800",
        "featured": False,
    },
    {
        "title": "Simplilearn",
        "description": "World's #1 online bootcamp.",
        "why_this_product": "🎓 Get certified in high-growth digital roles",
        "price": 500.0,
        "category": "Learn",
        "type": "affiliate",
        "affiliate_link": "https://www.simplilearn.com/",
        "affiliate_network": "Impact",
        "image_url": "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800",
        "featured": False,
    },
]

async def seed_platforms():
    print(f"Connecting to MongoDB at {mongo_url}...")
    
    # Optional: Clear existing platform products first
    # await db.products.delete_many({"category": {"$in": ["Side Hustles", "AI Tools", "Learn"]}})
    
    products_to_insert = []
    for p in PLATFORM_PRODUCTS:
        product_id = str(uuid.uuid4())
        now = datetime.now(timezone.utc).isoformat()
        
        product_doc = {
            "id": product_id,
            "title": p["title"],
            "description": p["description"],
            "why_this_product": p["why_this_product"],
            "price": float(p["price"]),
            "category": p["category"],
            "type": p["type"],
            "affiliate_link": p["affiliate_link"],
            "affiliateLink": p["affiliate_link"],
            "affiliate_network": p["affiliate_network"],
            "image_url": p["image_url"],
            "image": p["image_url"],
            "fullImage": p["image_url"],
            "featured": p["featured"],
            "premium": False,
            "verified": True,
            "clicks": 0,
            "rating": 4.5,
            "review_count": 100,
            "created_at": now,
            "updated_at": now
        }
        products_to_insert.append(product_doc)
    
    if products_to_insert:
        result = await db.products.insert_many(products_to_insert)
        print(f"Successfully added {len(result.inserted_ids)} platform products.")
    else:
        print("No products to add.")

if __name__ == "__main__":
    asyncio.run(seed_platforms())
