$products = @(
    @{ title='Jasper AI (formerly Jarvis)'; description='AI writing assistant for marketing, blog posts, ads, emails, social media'; why_this_product='Create copy 5x faster, proven for affiliate SEO wins'; category='AI Tools'; type='affiliate'; price=59.0; original_price=99.0; affiliate_link='https://shareasale.com/r.cfm?b=12345&u=678901&m=11111'; affiliate_network='ShareASale'; image_url='https://images.unsplash.com/photo-1677442d019cecf8bda336186fa506c3fa6a404eb?w=500&h=300&fit=crop'; featured=$false; premium=$false }
    @{ title='ConvertKit Email Marketing'; description='Email automation for creators, landing pages, funnels'; why_this_product='Email list growth + passive revenue with automation'; category='AI Tools'; type='affiliate'; price=29.0; original_price=49.0; affiliate_link='https://convertkit.com/?_ke=XYZ'; affiliate_network='ConvertKit'; image_url='https://images.unsplash.com/photo-1626785774573-4b799315345d?w=500&h=300&fit=crop'; featured=$false; premium=$false }
    @{ title='AWeber Newsletter Platform'; description='Drag-and-drop email builder + automations'; why_this_product='High deliverability for affiliate promotions'; category='Tech'; type='affiliate'; price=19.0; original_price=29.0; affiliate_link='https://www.aweber.com/affiliates.htm?ref=yourid'; affiliate_network='AWeber'; image_url='https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=500&h=300&fit=crop'; featured=$false; premium=$false }
    @{ title='NordVPN'; description='Secure VPN for privacy, streaming, remote work'; why_this_product='Essential digital safety product for every online business'; category='Home'; type='affiliate'; price=3.29; original_price=12.99; affiliate_link='https://get.nordvpn.com/aff_12345'; affiliate_network='ImpactRadius'; image_url='https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=300&fit=crop'; featured=$false; premium=$false }
    @{ title='Skillshare Annual'; description='Online courses for design, business, tech, entrepreneurship'; why_this_product='Reskill quickly with premium learning and income strategy'; category='Learn'; type='affiliate'; price=19.0; original_price=99.0; affiliate_link='https://www.skillshare.com/r/userid'; affiliate_network='CJ'; image_url='https://images.unsplash.com/photo-1516534775068-bb57e5a7bcd8?w=500&h=300&fit=crop'; featured=$false; premium=$false }
    @{ title='Digital Notion Planner Kit'; description='Downloadable Notion dashboard + templates for entrepreneurs'; why_this_product='Helps creators scale daily workflow fast'; category='Productivity'; type='marketplace'; price=14.99; original_price=29.99; affiliate_link='https://gumroad.com/l/notion-pro-plan'; affiliate_network='Gumroad'; image_url='https://images.unsplash.com/photo-1611224556348-cfb9dc5d7fbb?w=500&h=300&fit=crop'; featured=$true; premium=$false }
    @{ title='Canva Social Media Template Bundle'; description='120+ Instagram/Reels templates + branding set'; why_this_product='Instantly look pro and save 10+ hours/week'; category='Design'; type='marketplace'; price=29.0; original_price=59.0; affiliate_link='https://linktr.ee/mycanvapack'; affiliate_network='Self'; image_url='https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?w=500&h=300&fit=crop'; featured=$true; premium=$false }
    @{ title='Printable Budget Tracker PDF'; description='Budget planner, debt payoff, savings goals printable PDF'; why_this_product='High repeat value for money management audience'; category='Finance'; type='marketplace'; price=7.99; original_price=14.99; affiliate_link='https://payhip.com/budget-pro'; affiliate_network='Payhip'; image_url='https://images.unsplash.com/photo-1579621970563-430f63602022?w=500&h=300&fit=crop'; featured=$false; premium=$false }
    @{ title='Freelancer Proposal Template'; description='Editable proposal + contract template for service providers'; why_this_product='Close clients 2x faster and reduce negotiation friction'; category='Business'; type='marketplace'; price=19.9; original_price=39.9; affiliate_link='https://sellfy.com/p/xyz/proposal-template'; affiliate_network='Sellfy'; image_url='https://images.unsplash.com/photo-1586281380349-2c8b6744a0c7?w=500&h=300&fit=crop'; featured=$false; premium=$false }
    @{ title='3D Printed Phone Stand'; description='Ergonomic desktop phone stand for desk/zoom/youtube creators'; why_this_product='A small physical item with high ROI and fast shipping'; category='Tech'; type='marketplace'; price=14.99; original_price=29.99; affiliate_link='https://tropicalplants.com/shop/phone-stand'; affiliate_network='Shopify'; image_url='https://images.unsplash.com/photo-1556656793-08538906a9f8?w=500&h=300&fit=crop'; featured=$false; premium=$false }
    @{ title='LED Ring Light w/ Tripod'; description='10-inch dimmable ring light + phone holder'; why_this_product='Best seller for creators and live streamers'; category='Tech'; type='dropshipping'; price=24.95; original_price=49.9; affiliate_link='https://www.aliexpress.com/item/100500123456789.html'; affiliate_network='AliExpress'; image_url='https://images.unsplash.com/photo-1693514789515-786287a63e5f?w=500&h=300&fit=crop'; featured=$false; premium=$false }
    @{ title='Portable USB Blender'; description='Rechargeable personal blender for smoothies, travel'; why_this_product='Convenient health gadget and impulse purchase'; category='Fitness'; type='dropshipping'; price=22.9; original_price=39.9; affiliate_link='https://www.aliexpress.com/item/100500987654321.html'; affiliate_network='AliExpress'; image_url='https://images.unsplash.com/photo-1611080626919-d2ddd0863006?w=500&h=300&fit=crop'; featured=$false; premium=$false }
    @{ title='Smartwatch Fitness Tracker'; description='Heart rate, SpO2, sleep, steps with smartphone app'; why_this_product='High conversion in wellness audience'; category='Health'; type='dropshipping'; price=31.5; original_price=59.9; affiliate_link='https://www.aliexpress.com/item/100500543216789.html'; affiliate_network='AliExpress'; image_url='https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&h=300&fit=crop'; featured=$false; premium=$false }
    @{ title='Foldable Laptop Stand'; description='Adjustable laptop riser with cooling airflow'; why_this_product='Work-from-home essential, high demand'; category='Home'; type='dropshipping'; price=18.7; original_price=34.9; affiliate_link='https://www.aliexpress.com/item/100500555111777.html'; affiliate_network='AliExpress'; image_url='https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500&h=300&fit=crop'; featured=$false; premium=$false }
    @{ title='Blue Light Blocking Glasses'; description='Anti-eye strain computer glasses for long screen sessions'; why_this_product='Recurring reorders for office / gamer niches'; category='Fashion'; type='dropshipping'; price=11.99; original_price=24.99; affiliate_link='https://www.aliexpress.com/item/100500222333444.html'; affiliate_network='AliExpress'; image_url='https://images.unsplash.com/photo-1508181585858-08f498b786e7?w=500&h=300&fit=crop'; featured=$false; premium=$false }
    @{ title='Local SEO GMB Setup Service'; description='Setup and optimize Google Business Profile for local SMBs'; why_this_product='Easy service business with recurring maintenance contracts'; category='Idea'; type='idea'; price=299.0; original_price=499.0; affiliate_link='https://www.yoursite.com/service/gmb-setup'; affiliate_network='Own'; image_url='https://images.unsplash.com/photo-1460925895917-adf4e565e6c1?w=500&h=300&fit=crop'; featured=$false; premium=$false }
    @{ title='AI Resume + Cover Letter Service'; description='AI-assisted resume + cover letter personalization for job seekers'; why_this_product='High demand and easy to scale via templates'; category='Idea'; type='idea'; price=79.0; original_price=149.0; affiliate_link='https://www.yoursite.com/service/ai-resume'; affiliate_network='Own'; image_url='https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=300&fit=crop'; featured=$false; premium=$false }
    @{ title='Subscription Content Calendar Package'; description='Monthly done-for-you social media content calendar + captions'; why_this_product='Recurring revenue and low production cost after template setup'; category='Idea'; type='idea'; price=49.0; original_price=99.0; affiliate_link='https://www.yoursite.com/service/content-calendar'; affiliate_network='Own'; image_url='https://images.unsplash.com/photo-1518718014496-de42cc929fcd?w=500&h=300&fit=crop'; featured=$false; premium=$false }
    @{ title='Affiliate Email Funnel in 7 Days'; description='Guided program with 7 email sequences for selling top affiliate products'; why_this_product='Monetize audiences fast with automated funnels'; category='Idea'; type='idea'; price=149.0; original_price=299.0; affiliate_link='https://www.yoursite.com/service/email-funnel'; affiliate_network='Own'; image_url='https://images.unsplash.com/photo-1556740738-b6a63e27c4df?w=500&h=300&fit=crop'; featured=$false; premium=$false }
    @{ title='Print-on-Demand Merch Store Setup'; description='Setup and consultant package for Shopify + Printful niche store'; why_this_product='Low upfront cost, high scaling potential'; category='Idea'; type='idea'; price=39.0; original_price=79.0; affiliate_link='https://www.yoursite.com/service/pod-store'; affiliate_network='Own'; image_url='https://images.unsplash.com/photo-1523206489230-c012066d937a?w=500&h=300&fit=crop'; featured=$false; premium=$false }
)
$url = 'http://127.0.0.1:8000/api/products'
foreach ($p in $products) {
    try {
        $body = $p | ConvertTo-Json -Depth 5
        Invoke-RestMethod -Uri $url -Method Post -ContentType 'application/json' -Body $body
        Write-Host "Created: $($p.title)"
    } catch {
        Write-Host "Error: $($p.title) - $($_.Exception.Message)"
    }
}